### ISSUE TITLE
Framework build fails when building for armv7 and arm64

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1567]
Hi,

I am building j2objc for those platforms:

`export J2OBJC_ARCHS="macosx iphone64 iphone64e watchv7k watch64 watchsimulator simulator64 maccatalyst iphone simulator"`

Then I build everything:

`make -j8 all_dist`

The build finish with:

```
building JRE framework
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/maccatalyst/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/macosx/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-simulator/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-simulator64/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-watch64/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-watchsimulator/libjre_emul.a
Both ios-arm64 and ios-armv7 represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [frameworks] Error 2
```

I am not sure, how armv7 (32 bit) and arm64 (64) could be equivalent...

**Comment by tomball** [comment]
Fixed.

**Comment by himamis** [comment]
I am still getting this issue on master and on tag 2.8.
This is the part that fails
```
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/balazs/workspace/j2objc/jre_emul/build_result/objs-iphone/libjre_emul.a -library /Users/balazs/workspace/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a -library /Users/balazs/workspace/j2objc/jre_emul/build_result/objs-simulator/libjre_emul.a -library /Users/balazs/workspace/j2objc/jre_emul/build_result/objs-simulator64/libjre_emul.a
```
This is the command that I call
```
make -j8 frameworks
```

I am running this on a m1 Mac. Could this be the cause?

**Comment by tomball** [comment]
That may be the issue, and I don't have access to any M1 hardware. As you
can see, all that command does is specify which libraries to include in the
framework, so what's the error? Is it a problem with one of the libraries?
Is the problem that one you need is missing?

To make sure the libraries aren't fat, you can run `lipo -info
build_result/objs-*/libjre_emul.a`. That should generate the same list of
libraries as used for the xcodebuild, and lipo should state each is a
"Non-fat file".

**Comment by tomball** [comment]
That may be the issue, and I don't have access to any M1 hardware. As you can see, all that command does is specify which libraries to include in the framework, so what's the error? Is it a problem with one of the libraries? Is the problem that one you need is missing?

To make sure the libraries aren't fat, you can run `lipo -info build_result/objs-*/libjre_emul.a`. That should generate the same list of libraries as used for the xcodebuild, and lipo should state each is a
"Non-fat file".

**Comment by himamis** [comment]
When calling with environment
```
J2OBJC_ARCHS=iphone iphone64
```
at generating JRE frameworks
```
building jre_emul archs: iphone iphone64
building JRE framework
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/balazs/workspace/j2objc2/jre_emul/build_result/objs-iphone/libjre_emul.a -library /Users/balazs/workspace/j2objc2/jre_emul/build_result/objs-iphone64/libjre_emul.a
```
The command is called with separate slices, but it fails with the error
```
Both ios-armv7 and ios-arm64 represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [frameworks] Error 2
```
xcodebuild documentation is not very helpful with this one.

**Comment by himamis** [comment]
I'm not sure if this is j2objc build issue, or xcodebuild bug/missing feature.

**Comment by tomball** [comment]
Apparently fat libraries are not to be used for iOS, watchOS, or AppleTV, but *are* required for macOS: https://developer.apple.com/forums/thread/666335

Apparently they didn't feel the need to document this other than in a discussion thread. 🤬

**Comment by tomball** [comment]
Fixed in current source.

**Comment by sarsonj** [comment]
Hi,

I still have same problem with current sources:

`export J2OBJC_ARCHS="iphone64 simulator64 iphone"`
`make -j8 all_dist`

result:
```
building JRE framework
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone/libjre_emul.a -library /Users/sarsonj/work/git/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a
Both ios-armv7 and ios-arm64 represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [frameworks] Error 2
```

**Comment by tomball** [comment]
Why are you building a 32-bit iPhone arch? My limited understanding is that Apple won't accept 32-bit apps any more.

**Comment by sarsonj** [comment]
We are still supports iPhone 5 / iOS 10 - it means ARMv7. I didn't noticed, that armv7 is not supported anymore. It is not possible to send 32bit only build, but 64bit with 32bit fat binary is still allowed.
