### ISSUE TITLE
j2objc - building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

### ISSUE THREAD

**Issue by Kajal-ithena** [google/j2objc#1697]
Getting below error while running application for iOS deveices: 
j2objc-dist/lib/libjre_emul.a(IOSClass.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by tomball** [comment]
Is it really an error, as in, the build fails to complete? Messages like that are generally warnings.

Have you cloned [j2objc's repository](https://github.com/google/j2objc), then [built it](https://developers.google.com/j2objc/guides/building-j2objc) and used that new distribution building your app? The release bundles are intended to just a starting point for new j2objc users.

**Comment by tomball** [comment]
Since 2.8, we've fixed several issues with xcframework generation, due to Xcode 12.4/12.5 changes as well as support for Mac M1 systems. Please clone our repository, then [build it](https://developers.google.com/j2objc/guides/building-j2objc) -- if you want to continue working with a distribution bundle, you can run [scripts/build_distribution.sh](https://github.com/google/j2objc/blob/master/scripts/build_distribution.sh) with your own version number. Please reopen this issue if you still have problems with a a bundle built from the latest source.

FYI, the Maven plugin was developed by external developers who have long since stopped working on it. It's great as long as it keeps working for you, but be aware it's passed its end-of-life. The Gradle plugin has also been dropped by its contributors, but was written more recently. We're working on j2objc support using Bazel (https://bazel.build/), which though less popular publicly is what Google uses internally.

**Comment by p-mazhnik** [comment]
@tomball  Still getting this error while running application for iOS, both for `master` and 2.8.   
But seems that it only happened with some libraries -- for me this is `javax.inject`:  

> in j2objc/lib/libjavax_inject.a(Named.o), building for iOS Simulator, but linking in object file built for iOS, file 'j2objc/lib/libjavax_inject.a' for architecture arm64.  

Is it possible that something is wrong with this library?

I have Mac M1, Xcode 12.5 and everything works fine with Rosetta x86_64 emulation

**Comment by tomball** [comment]
It's possible that you didn't run "make clean" in the master's top-level directory ("j2objc"), before building it. All libraries use the same build definitions in j2objc/make, so they should either all work or all fail.
