### ISSUE TITLE
Access Enums in Swift more simple

### ISSUE THREAD

**Issue by confile** [google/j2objc#520]
As I described [here](http://stackoverflow.com/questions/29613522/access-enum-translated-with-j2objc-in-swift/29623249#29623249) it is hard to access Java Enums from Swift. This can be done with: 

```
var r:BISBTestTypeEnum = BISBTestTypeEnum.values().objectAtIndex(BISBTestType.Type1.rawValue) as! BISBTestTypeEnum
```
As you can see it is very long. It would be great if you could add one helper method to make such access more simple. 

If you would add a method like this (Swift): 

```
    class func withValue(value: BISBTestType) -> BISBTestTypeEnum {
        return BISBTestTypeEnum.values().objectAtIndex(value.rawValue) as! BISBTestTypeEnum
    }
```
in Objective-C I guess that is something like this:
```
+ (BISBTestTypeEnum *)valueOfWithNSString:(BISBTestType *)value {
  return [[BISBTestTypeEnum values] objectAtIndex:[value rawValue]];
}
```

you can access Enums as: 
```
var r = BISBTestTypeEnum.withValue(BISBTestType.Type1)
```

**Comment by tomball** [comment]
While we're working on making the translator generate better enum code, today you can access the enum constant object using:

var r:BISBTestTypeEnum = BISBTestTypeEnum_values_[BISBTestType_Type1];

Still too ugly, but simpler because BISBTestTypeEnum_values_ is already typed, and BISBTestType_Type1 is an int constant.

**Comment by tomball** [comment]
Added --static-accessor-methods flag, which adds class methods to access static accessor functions and enum constants from Swift. This should now work:

var r:BISBTestTypeEnum = BISBTestTypeEnum.Type1()

**Comment by confile** [comment]
That is great thank you.

**Comment by confile** [comment]
@tomball Could you please add this to the docs.

**Comment by confile** [comment]
Xcode reports a lot of error when I use this flag. The errors are all in the generated files. Here is an example. It suggest to replace code in a translated file:

![parameterconfig_m](https://cloud.githubusercontent.com/assets/64265/7701435/61fa6154-fe27-11e4-8d6c-123da1c01b22.png)

The Java class was: 
```
public final class ParameterConfig {
   public static final int MAX_ITEMS_LOADED = 9; 
}

```

**Comment by tomball** [comment]
[Just pushed a fix](https://github.com/google/j2objc/commit/dc87214fd42389962f788b1838b362762d79d3b7)

**Comment by confile** [comment]
Now the error has changed to: 

```
Undefined symbols for architecture i386:
  "_AsyncCallFailEvent_set_TYPE_", referenced from:
      +[TestCorePrototypeMvpProxyAsyncCallFailEvent setTYPE:] in libPods-Test-test-main.a(AsyncCallFailEvent.o)

```

**Comment by kstanger** [comment]
I've pushed another fix
<https://github.com/google/j2objc/commit/abe2bb21579bdd1889b2a16211ef03810cd11fdf>
about a week ago. Try again.

**Comment by confile** [comment]
@kstanger No still not solved. Here is the error: 

![buddyis_xcworkspace](https://cloud.githubusercontent.com/assets/64265/7947719/2a99860a-097f-11e5-97f7-88cf644e9988.png)

**Comment by kstanger** [comment]
Can you provide the Java and Objective-C declarations for the
CurrentUserUpdatedEvent.TYPE field?

**Comment by confile** [comment]
@kstanger sure here it is: 
Java:
```
public class CurrentUserUpdatedEvent extends AbstractBEvent<CurrentUserUpdatedEvent.CurrentUserUpdatedHandler> {

  public static Type<CurrentUserUpdatedHandler> TYPE = new Type<CurrentUserUpdatedHandler>();
  
  public interface CurrentUserUpdatedHandler extends BEventHandler {
    void onCurrentUserUpdated(CurrentUserUpdatedEvent event);
  }
  
  @Override
  public AbstractBEvent.Type<CurrentUserUpdatedHandler> getAssociatedType() {
    return TYPE;
  }
  
  public static Type<CurrentUserUpdatedHandler> getType() {
    return TYPE;
  }

  @Override
  protected void dispatch(CurrentUserUpdatedHandler handler) {
    handler.onCurrentUserUpdated(this);
  }
  
  public static void fire(BHasHandlers source) {
    source.fireEvent(new CurrentUserUpdatedEvent());
  }
   
  
}
```
Objective-c

[CurrentUserUpdatedEvent.h](https://gist.github.com/confile/a2bce4f160a4cd957ed1)
[CurrentUserUpdatedEvent.m](https://gist.github.com/confile/70a16bba4947b9b27034)

**Comment by confile** [comment]
Hope this helps.

**Comment by kstanger** [comment]
Found the bug. We're not adding the package prefix in the "_set_" call.
I'll have a fix out by next week.

To fix this locally:
https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/gen/TypeImplementationGenerator.java#L157
change "typeBinding.getName()" to "typeName".

**Comment by confile** [comment]
@kstanger thank you for helping me with this Keith. I will test this and give you feedback.

**Comment by confile** [comment]
@kstanger This issue is solved with your last fix.
