### ISSUE TITLE
classpath for aar

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#885]
we`ve been using j2objc for quite some time. it works really great, it is a rock solid tool.
it would be wonderful if we can pass aar as classpath to j2objc directly, instead of manually unzip aar and pass 'classes.jar'

sorry cannot provide any aar since company security. Basically, one can open Android Studio, create Android Library module, run gradle build, an aar will be generated

**Comment by lancemao** [comment]
what I was asking is to add specific aar file as classpath instead of source file. e.g.

j2objc -use-arc -d out -sourcepath android `find android -name '*.java'` -classpath file1.jar:file2.jar:file3.aar

note file3.aar added as -classpath

sorry for the confusion

**Comment by tomball** [comment]
javac does not support aar files, so to provide this support aar files will need to be expanded and their classes.jar substituted. Similar processing should be done for source paths, to avoid any confusion over what does and doesn't work in the future. 

Unless you want to try updating how [Options.processArg()](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/Options.java#L248) handles aar files in source and class paths, I'll work on it this weekend.

Thanks for the tip on how to generate aar files. As you can probably guess, we aren't Android developers. :-)

**Comment by lancemao** [comment]
sure. I will give it a try.

**Comment by tomball** [comment]
Please don't waste your time, as I just finished this and set it out for review. It was more complicated than expected, mostly because the test found that FileUtil.extractZipEntry() corrupted zip entries that weren't source files.

**Comment by tomball** [comment]
Fixed in current source.

**Comment by lancemao** [comment]
on latest release, 2.0.4.1
aar still not working, please take a look

**Comment by tomball** [comment]
Please be more specific, as "still not working" is not a reasonable bug description.

The change I made extracts the `classes.jar` entry from a specified `*.aar` file. Please run `unzip -l` on any aar file that isn't being read to verify it has a `classes.jar` entry, without any prefix. If the classes.jar has a different name or path, then let me know what it is and how you created the aar file, since `classes.jar` is both the documented path and what I found after creating a test aar file in Android Studio.

One possible issue that also exists with javac (last time I checked) is that with any source or class path that includes '~' home directory references, only the first is expanded by bash. For example on my system, `-classpath ~/jars/junit.jar:~/jars/hamcrest-core-1.1.jar` is expanded to `-classpath /Users/tball/jars/junit.jar:~/jars/hamcrest-core-1.1.jar`. The workaround is to use `$HOME` instead of '`', since each `$HOME` reference is expanded by bash.
